name: Update Git Submodule
description: Pulls the latest changes from a submodule and updates the pointer.
inputs:
  path:
    description: 'Submodule path'
    require: true
    default: '.'
  branch:
    description: 'Branch to track'
    require: true
    default: 'main'

runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ inputs.path }}
        git fetch origin
        git checkout origin/${{ inputs.branch }}
        cd -
        git add ${{ inputs.path }}
    - run: |
        if ! git diff --cached --quiet; then
          git config user.name "ianhub-bot"
          git config user.email "bot@ianhub.net"
          git commit -m "🔄 Update submodule at ${{ inputs.path }}"
          git push
        else
          echo "✅ Submodule already up to date"
        fi
      shell: bash