name: Notify CSK Projects
description: Send notification to projects about pushed updates.
inputs:
  token:
    description: 'GitHub token with repo access'
    required: true
  event:
    description: 'Dispatch event name'
    required: true
    default: core-update
  projects:
    description: Pipe-separated project list.
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Fetch centralized CSK_PROJECTS if not provided
        if [ -z "${{ inputs.projects }}" ]; then
          echo "🧬 No projects passed. Fetching from ianhubnet/github-actions..."
          CSK_PROJECTS=$(curl -s -H "Authorization: Bearer ${{ inputs.token }}" \
            https://api.github.com/repos/ianhubnet/github-actions/actions/variables/CSK_PROJECTS \
            | jq -r '.value')
        else
          CSK_PROJECTS="${{ inputs.projects }}"
        fi

        IFS='|' read -ra REPOS <<< "$CSK_PROJECTS"
        for REPO in "${REPOS[@]}"; do
          if [[ "$REPO" == */* ]]; then
            TARGET_REPO="$REPO"
          else
            TARGET_REPO="ianhubnet/$REPO"
          fi

          echo "🚀 Dispatching '${{ inputs.event }}' to $TARGET_REPO..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            "https://api.github.com/repos/$TARGET_REPO/dispatches" \
            -d "{\"event_type\":\"${{ inputs.event }}\"}"
        done